name: 'Terraform Azure CI/CD'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest

    env:
       ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CLIENT_ID }}
       TF_VAR_vm_admin_password: ${{ secrets.VM_ADMIN_PASSWORD }}

    steps:
    # 1 - Taking code from repository to a robot
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2 - Loging to Azure using secrets
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CLIENT_ID }}

    # 3 - Instalattion and configuration robot
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # 4 - Initialization Terraform 
    - name: Terraform Init
      run: terraform init

    # 5 - Generating a change plan
    - name: Terraform Plan
      run: terraform plan -input=false

    # 6 - Apply and push
    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
    
